### ISSUE TITLE
IncompleteRexProRequestException: Message envelope is incomplete

### ISSUE THREAD

**Issue by edi-bice** [platinummonkey/rexpro-python#15]
I get a ton of these in titan-server-0.4.4/log/rextitan.log:

Grizzly(3)] WARN  com.tinkerpop.rexster.protocol.filter.RexProServerFilter  - com.tinkerpop.rexster.protocol.server.IncompleteRexProRequestException: Message envelope is incomplete. Message length set to 4617 but the buffer only contains 1448

I assume it belongs here since I'm using rexpro-python (0.3.3) on the client to submit requests to the server where I'm seeing these.

**Comment by platinummonkey** [comment]
Interesting, I've never seen this myself, do you happen to know what query is being sent? (is it supposed to be the former or latter?)

**Comment by edi-bice** [comment]
How can I tell? Do you know of any settings I can turn on server-side to see the query? I will look myself as well. FYI, upgraded to the latest rexpro-python package in DEV going against titan-server-0.4.4 as well and haven't seen the "envelope is incomplete" warning yet.

**Comment by platinummonkey** [comment]
hm, wondering if there was just some msgpack formatting issue?

**Comment by platinummonkey** [comment]
@edi-bice I think this issue might have been resolved with the help of https://github.com/platinummonkey/rexpro-python/pull/19

**Comment by edi-bice** [comment]
@platinummonkey I am no longer using and can't verify - closing.
