### ISSUE TITLE
Polling for features unnecessarily

### ISSUE THREAD

**Issue by atomos** [platinummonkey/rexpro-python#17]
Hi,

We noticed that the rexpro client was frequently polling for features (g.getFeatures().toMap()). We saw it executing this query in rexpro/connectors/base.py when a new session is created, but nothing ever uses the result. Can this be removed? We deleted it in our fork and everything seems to be working.

Adam

**Comment by platinummonkey** [comment]
Don't see why not! Can you submit a pull request?

**Comment by atomos** [comment]
Just did. Thanks!

https://github.com/platinummonkey/rexpro-python/pull/18

**Comment by platinummonkey** [comment]
merged, deploying new point version.

**Comment by platinummonkey** [comment]
0.4.4 released
